flyway:
  schemas: PUBLIC
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:prod;mode=PostgreSQL;DB_CLOSE_DELAY=-1
    password: sa
    username: sa
  jpa:
    hibernate:
      show-sql: false
    properties:
      hibernate:
        format_sql: false
